steps:
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'gs://ctm-environment-prod/app/.env', '.env']

  - name: 'environment variables'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        export $(grep -v '^#' .env | xargs) && \
        ENV_VARS=$(grep -v '^#' .env | xargs | sed 's/ /,/g') && \
        echo $ENV_VARS > /workspace/env_vars.txt

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/chess-tactics-manager-app', '-f', './Dockerfile', '..']
    dir: 'app'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/chess-tactics-manager-app']

  - name: 'deploy to Cloud Run'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        ENV_VARS=$(cat /workspace/env_vars.txt) && \
        gcloud run deploy chess-tactics-manager-app \
          --image gcr.io/$PROJECT_ID/chess-tactics-manager-app \
          --platform managed \
          --region europe-west1 \
          --allow-unauthenticated \
          --port 8080 \
          --set-env-vars $ENV_VARS

images:
  - 'gcr.io/$PROJECT_ID/chess-tactics-manager-app'
  
options:
  logging: CLOUD_LOGGING_ONLY
