steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/chess-tactics-manager-app:${_COMMIT_SHA}', '-f', './Dockerfile', '..']
    dir: 'app'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/chess-tactics-manager-app:${_COMMIT_SHA}']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'chess-tactics-manager-app'
      - '--image'
      - 'gcr.io/$PROJECT_ID/chess-tactics-manager-app:${_COMMIT_SHA}'
      - '--platform'
      - 'managed'
      - '--region'
      - 'europe-west1'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'

substitutions:
  _BRANCH: ${_BRANCH}
  _COMMIT_SHA: ${_COMMIT_SHA}

images:
  - 'gcr.io/$PROJECT_ID/chess-tactics-manager-app:${_COMMIT_SHA}'

options:
  logging: CLOUD_LOGGING_ONLY
