name: Application CI

on:
  pull_request:
    paths:
      - app/**
      - '.github/workflows/ci_app.yml'
    
jobs:
  app:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          service_account_key: ${{ secrets.GOOGLE_CREDENTIALS }}
          project_id: 'chess-tactics-manager-ci'

      - name: Run Cloud Build
        run: |
          COMMIT_SHA=$(git rev-parse --short HEAD)
          BRANCH=$(git rev-parse --abbrev-ref HEAD)
          gcloud builds submit --config app/cloudbuild.yaml .. --substitutions=_BRANCH=$BRANCH,COMMIT_SHA=$COMMIT_SHA