name: Application CI

on:
  pull_request:
    paths:
      - app/**
      - '.github/workflows/ci_app.yml'
    
jobs:
  app:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          project_id: 'chess-tactics-manager-ci'

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Get current Git commit SHA
        id: vars
        run: |
          echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "BRANCH=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
  
      - name: Run Cloud Build
        run: |
          gcloud builds submit --config app/cloudbuild.yaml ..