name: Check application build

on:
  pull_request:
    paths:
      - 'app/**'


jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
        
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: pnpm install

      - name: Lint with ESLint
        run: pnpm run lint

      - name: Build with Next.js
        run: pnpm run build
